apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-1g-pv
  namespace: geraldkohn
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage-class
  hostPath:
    path: /tmp/data/redis/
