// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: internal/api/chat/chat.proto

package pbChat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端发送消息, 服务端返回消息, 处理消息都是这个消息体.
// 重复使用, 字段不需要可以暂时不填充
type MsgFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatType    int32  `protobuf:"varint,1,opt,name=ChatType,proto3" json:"ChatType,omitempty"`       // 聊天类型(单聊, 群聊)
	SendID      string `protobuf:"bytes,2,opt,name=SendID,proto3" json:"SendID,omitempty"`            // 发送方
	RecvID      string `protobuf:"bytes,3,opt,name=RecvID,proto3" json:"RecvID,omitempty"`            // 接收方
	GroupID     string `protobuf:"bytes,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`          // 群组号
	SendTime    int64  `protobuf:"varint,5,opt,name=SendTime,proto3" json:"SendTime,omitempty"`       // 发送时间
	Sequence    int64  `protobuf:"varint,6,opt,name=Sequence,proto3" json:"Sequence,omitempty"`       // 序列号
	ContentType int32  `protobuf:"varint,7,opt,name=ContentType,proto3" json:"ContentType,omitempty"` // 消息类型
	Content     []byte `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`          // 消息体
}

func (x *MsgFormat) Reset() {
	*x = MsgFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFormat) ProtoMessage() {}

func (x *MsgFormat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFormat.ProtoReflect.Descriptor instead.
func (*MsgFormat) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *MsgFormat) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *MsgFormat) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *MsgFormat) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *MsgFormat) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *MsgFormat) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MsgFormat) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MsgFormat) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *MsgFormat) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type MsgFormatList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgFormats []*MsgFormat `protobuf:"bytes,1,rep,name=MsgFormats,proto3" json:"MsgFormats,omitempty"`
}

func (x *MsgFormatList) Reset() {
	*x = MsgFormatList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFormatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFormatList) ProtoMessage() {}

func (x *MsgFormatList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFormatList.ProtoReflect.Descriptor instead.
func (*MsgFormatList) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *MsgFormatList) GetMsgFormats() []*MsgFormat {
	if x != nil {
		return x.MsgFormats
	}
	return nil
}

// Websocket 连接通用请求消息, 具体消息填充到 Data 字段
type WSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action int32  `protobuf:"varint,1,opt,name=Action,proto3" json:"Action,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *WSRequest) Reset() {
	*x = WSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSRequest) ProtoMessage() {}

func (x *WSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSRequest.ProtoReflect.Descriptor instead.
func (*WSRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *WSRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *WSRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WSRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 需要填充到 WSRequest 的 Data 字段
// 根据序列号范围拉取消息
type PullMsgBySeqRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqBegin int64 `protobuf:"varint,1,opt,name=SeqBegin,proto3" json:"SeqBegin,omitempty"`
	SeqEnd   int64 `protobuf:"varint,2,opt,name=SeqEnd,proto3" json:"SeqEnd,omitempty"`
}

func (x *PullMsgBySeqRangeRequest) Reset() {
	*x = PullMsgBySeqRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMsgBySeqRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgBySeqRangeRequest) ProtoMessage() {}

func (x *PullMsgBySeqRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgBySeqRangeRequest.ProtoReflect.Descriptor instead.
func (*PullMsgBySeqRangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *PullMsgBySeqRangeRequest) GetSeqBegin() int64 {
	if x != nil {
		return x.SeqBegin
	}
	return 0
}

func (x *PullMsgBySeqRangeRequest) GetSeqEnd() int64 {
	if x != nil {
		return x.SeqEnd
	}
	return 0
}

// 需要填充到 WSRequest 的 Data 字段
// 根据序列号列表拉取消息
type PullMsgBySeqListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqList []int64 `protobuf:"varint,1,rep,packed,name=SeqList,proto3" json:"SeqList,omitempty"`
}

func (x *PullMsgBySeqListRequest) Reset() {
	*x = PullMsgBySeqListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMsgBySeqListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgBySeqListRequest) ProtoMessage() {}

func (x *PullMsgBySeqListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgBySeqListRequest.ProtoReflect.Descriptor instead.
func (*PullMsgBySeqListRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *PullMsgBySeqListRequest) GetSeqList() []int64 {
	if x != nil {
		return x.SeqList
	}
	return nil
}

// 需要填充到 WSRequest 的 Data 字段
// 获取用户最新序列号
type GetUserMaxSeqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserMaxSeqRequest) Reset() {
	*x = GetUserMaxSeqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMaxSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMaxSeqRequest) ProtoMessage() {}

func (x *GetUserMaxSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMaxSeqRequest.ProtoReflect.Descriptor instead.
func (*GetUserMaxSeqRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{5}
}

// 需要填充到 WSRequest 的 Data 字段
// 客户端向服务端发送消息
type PushMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgFormat *MsgFormat `protobuf:"bytes,1,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
}

func (x *PushMsgRequest) Reset() {
	*x = PushMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgRequest) ProtoMessage() {}

func (x *PushMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgRequest.ProtoReflect.Descriptor instead.
func (*PushMsgRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *PushMsgRequest) GetMsgFormat() *MsgFormat {
	if x != nil {
		return x.MsgFormat
	}
	return nil
}

// Websocket 连接通用返回消息, 具体消息填充到 Data 字段
type WSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action    int32  `protobuf:"varint,1,opt,name=Action,proto3" json:"Action,omitempty"`
	ErrorCode int32  `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg  string `protobuf:"bytes,3,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Data      []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *WSResponse) Reset() {
	*x = WSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSResponse) ProtoMessage() {}

func (x *WSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSResponse.ProtoReflect.Descriptor instead.
func (*WSResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *WSResponse) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *WSResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WSResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *WSResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 填充到 WSResponse 的 Data 字段
// 根据序列号范围拉取消息
type PullMsgBySeqRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgFormats []*MsgFormat `protobuf:"bytes,1,rep,name=MsgFormats,proto3" json:"MsgFormats,omitempty"`
}

func (x *PullMsgBySeqRangeResponse) Reset() {
	*x = PullMsgBySeqRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMsgBySeqRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgBySeqRangeResponse) ProtoMessage() {}

func (x *PullMsgBySeqRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgBySeqRangeResponse.ProtoReflect.Descriptor instead.
func (*PullMsgBySeqRangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PullMsgBySeqRangeResponse) GetMsgFormats() []*MsgFormat {
	if x != nil {
		return x.MsgFormats
	}
	return nil
}

// 填充到 WSResponse 的 Data 字段
// 根据序列号列表拉取消息
type PullMsgBySeqListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgFormats []*MsgFormat `protobuf:"bytes,1,rep,name=MsgFormats,proto3" json:"MsgFormats,omitempty"`
}

func (x *PullMsgBySeqListResponse) Reset() {
	*x = PullMsgBySeqListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMsgBySeqListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMsgBySeqListResponse) ProtoMessage() {}

func (x *PullMsgBySeqListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMsgBySeqListResponse.ProtoReflect.Descriptor instead.
func (*PullMsgBySeqListResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *PullMsgBySeqListResponse) GetMsgFormats() []*MsgFormat {
	if x != nil {
		return x.MsgFormats
	}
	return nil
}

// 填充到 WSResponse 的 Data 字段
// 获取用户最大序列号
type GetUserMaxSeqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq int64 `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
}

func (x *GetUserMaxSeqResponse) Reset() {
	*x = GetUserMaxSeqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMaxSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMaxSeqResponse) ProtoMessage() {}

func (x *GetUserMaxSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMaxSeqResponse.ProtoReflect.Descriptor instead.
func (*GetUserMaxSeqResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserMaxSeqResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 填充到 WSResponse 的 Data 字段
// 客户端向服务端发送消息
type PushMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool `protobuf:"varint,1,opt,name=Succeed,proto3" json:"Succeed,omitempty"`
}

func (x *PushMsgResponse) Reset() {
	*x = PushMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_chat_chat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgResponse) ProtoMessage() {}

func (x *PushMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_chat_chat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgResponse.ProtoReflect.Descriptor instead.
func (*PushMsgResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *PushMsgResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

var File_internal_api_chat_chat_proto protoreflect.FileDescriptor

var file_internal_api_chat_chat_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x62, 0x43, 0x68, 0x61, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x76,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x63, 0x76, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x42,
	0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x31, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x73, 0x67,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0a, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x73, 0x22, 0x4d, 0x0a, 0x09, 0x57, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x4e, 0x0a, 0x18, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x53, 0x65,
	0x71, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x53, 0x65, 0x71, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x71,
	0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x65, 0x71, 0x45, 0x6e,
	0x64, 0x22, 0x33, 0x0a, 0x17, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x73, 0x67, 0x42, 0x79, 0x53, 0x65,
	0x71, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x53,
	0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41,
	0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x73, 0x67,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x09, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x22, 0x72, 0x0a, 0x0a, 0x57, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x19, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x73, 0x67,
	0x42, 0x79, 0x53, 0x65, 0x71, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x43, 0x68, 0x61, 0x74, 0x2e,
	0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0a, 0x4d, 0x73, 0x67, 0x46, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x73, 0x22, 0x4d, 0x0a, 0x18, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x73, 0x67,
	0x42, 0x79, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d,
	0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0a, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x73, 0x22, 0x29, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x61, 0x78, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x53, 0x65, 0x71, 0x22,
	0x2b, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x3b, 0x70, 0x62, 0x43, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_chat_chat_proto_rawDescOnce sync.Once
	file_internal_api_chat_chat_proto_rawDescData = file_internal_api_chat_chat_proto_rawDesc
)

func file_internal_api_chat_chat_proto_rawDescGZIP() []byte {
	file_internal_api_chat_chat_proto_rawDescOnce.Do(func() {
		file_internal_api_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_chat_chat_proto_rawDescData)
	})
	return file_internal_api_chat_chat_proto_rawDescData
}

var file_internal_api_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_api_chat_chat_proto_goTypes = []interface{}{
	(*MsgFormat)(nil),                 // 0: pbChat.MsgFormat
	(*MsgFormatList)(nil),             // 1: pbChat.MsgFormatList
	(*WSRequest)(nil),                 // 2: pbChat.WSRequest
	(*PullMsgBySeqRangeRequest)(nil),  // 3: pbChat.PullMsgBySeqRangeRequest
	(*PullMsgBySeqListRequest)(nil),   // 4: pbChat.PullMsgBySeqListRequest
	(*GetUserMaxSeqRequest)(nil),      // 5: pbChat.GetUserMaxSeqRequest
	(*PushMsgRequest)(nil),            // 6: pbChat.PushMsgRequest
	(*WSResponse)(nil),                // 7: pbChat.WSResponse
	(*PullMsgBySeqRangeResponse)(nil), // 8: pbChat.PullMsgBySeqRangeResponse
	(*PullMsgBySeqListResponse)(nil),  // 9: pbChat.PullMsgBySeqListResponse
	(*GetUserMaxSeqResponse)(nil),     // 10: pbChat.GetUserMaxSeqResponse
	(*PushMsgResponse)(nil),           // 11: pbChat.PushMsgResponse
}
var file_internal_api_chat_chat_proto_depIdxs = []int32{
	0, // 0: pbChat.MsgFormatList.MsgFormats:type_name -> pbChat.MsgFormat
	0, // 1: pbChat.PushMsgRequest.MsgFormat:type_name -> pbChat.MsgFormat
	0, // 2: pbChat.PullMsgBySeqRangeResponse.MsgFormats:type_name -> pbChat.MsgFormat
	0, // 3: pbChat.PullMsgBySeqListResponse.MsgFormats:type_name -> pbChat.MsgFormat
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_api_chat_chat_proto_init() }
func file_internal_api_chat_chat_proto_init() {
	if File_internal_api_chat_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_chat_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFormatList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMsgBySeqRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMsgBySeqListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMaxSeqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMsgBySeqRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMsgBySeqListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMaxSeqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_chat_chat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_chat_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_chat_chat_proto_goTypes,
		DependencyIndexes: file_internal_api_chat_chat_proto_depIdxs,
		MessageInfos:      file_internal_api_chat_chat_proto_msgTypes,
	}.Build()
	File_internal_api_chat_chat_proto = out.File
	file_internal_api_chat_chat_proto_rawDesc = nil
	file_internal_api_chat_chat_proto_goTypes = nil
	file_internal_api_chat_chat_proto_depIdxs = nil
}
