apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-test
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
              name: service
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT    #zookeeper连接地址，通过Headless Service 连接
              value: "zookeeper-0.zookeeper-svc.geraldkohn.svc.cluster.local:2181"
            - name: ALLOW_PLAINTEXT_LISTENER  # 必须填写，否则启动报错
              value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: '9092'
  selector:
    app: kafka

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: kafka-client
# spec:
#   type: NodePort
#   ports:
#     - port: 9092
#       targetPort: 9092
#       nodePort: 30092
#   selector:
#     app: kafka
