apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-local-1g-pv
  namespace: geraldkohn
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: kafka-storage-class
  hostPath:
    path: /tmp/data/kafka
