apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: geraldkohn
spec:
  selector:
    app: kafka-sts
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
  clusterIP: None
