// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: internal/api/gateway/gateway.proto

package pbGateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端发送消息, 服务端返回消息, 处理消息都是这个消息体.
// 重复使用, 字段不需要可以暂时不填充
type MsgFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatType    int32  `protobuf:"varint,1,opt,name=ChatType,proto3" json:"ChatType,omitempty"`       // 聊天类型(单聊, 群聊)
	SendID      string `protobuf:"bytes,2,opt,name=SendID,proto3" json:"SendID,omitempty"`            // 发送方
	RecvID      string `protobuf:"bytes,3,opt,name=RecvID,proto3" json:"RecvID,omitempty"`            // 接收方
	GroupID     string `protobuf:"bytes,4,opt,name=GroupID,proto3" json:"GroupID,omitempty"`          // 群组号
	SendTime    int64  `protobuf:"varint,5,opt,name=SendTime,proto3" json:"SendTime,omitempty"`       // 发送时间
	Sequence    int64  `protobuf:"varint,6,opt,name=Sequence,proto3" json:"Sequence,omitempty"`       // 序列号
	ContentType int32  `protobuf:"varint,7,opt,name=ContentType,proto3" json:"ContentType,omitempty"` // 消息类型
	Content     []byte `protobuf:"bytes,8,opt,name=Content,proto3" json:"Content,omitempty"`          // 消息体
}

func (x *MsgFormat) Reset() {
	*x = MsgFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_gateway_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFormat) ProtoMessage() {}

func (x *MsgFormat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_gateway_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFormat.ProtoReflect.Descriptor instead.
func (*MsgFormat) Descriptor() ([]byte, []int) {
	return file_internal_api_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *MsgFormat) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *MsgFormat) GetSendID() string {
	if x != nil {
		return x.SendID
	}
	return ""
}

func (x *MsgFormat) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *MsgFormat) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *MsgFormat) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *MsgFormat) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MsgFormat) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *MsgFormat) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PushMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgFormat *MsgFormat `protobuf:"bytes,1,opt,name=MsgFormat,proto3" json:"MsgFormat,omitempty"`
}

func (x *PushMsgReq) Reset() {
	*x = PushMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_gateway_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReq) ProtoMessage() {}

func (x *PushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_gateway_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReq.ProtoReflect.Descriptor instead.
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return file_internal_api_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushMsgReq) GetMsgFormat() *MsgFormat {
	if x != nil {
		return x.MsgFormat
	}
	return nil
}

type PushMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Online  bool   `protobuf:"varint,1,opt,name=Online,proto3" json:"Online,omitempty"`
	ErrCode int32  `protobuf:"varint,2,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
}

func (x *PushMsgResp) Reset() {
	*x = PushMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_gateway_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgResp) ProtoMessage() {}

func (x *PushMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_gateway_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgResp.ProtoReflect.Descriptor instead.
func (*PushMsgResp) Descriptor() ([]byte, []int) {
	return file_internal_api_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *PushMsgResp) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PushMsgResp) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *PushMsgResp) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_internal_api_gateway_gateway_proto protoreflect.FileDescriptor

var file_internal_api_gateway_gateway_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22,
	0xe5, 0x01, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x76, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x63, 0x76, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x09,
	0x4d, 0x73, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x57, 0x0a, 0x0b, 0x50, 0x75, 0x73,
	0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72,
	0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4d,
	0x73, 0x67, 0x32, 0x40, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x38, 0x0a, 0x07, 0x50, 0x75,
	0x73, 0x68, 0x4d, 0x73, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70,
	0x62, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x3b, 0x70, 0x62, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_api_gateway_gateway_proto_rawDescOnce sync.Once
	file_internal_api_gateway_gateway_proto_rawDescData = file_internal_api_gateway_gateway_proto_rawDesc
)

func file_internal_api_gateway_gateway_proto_rawDescGZIP() []byte {
	file_internal_api_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_internal_api_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_gateway_gateway_proto_rawDescData)
	})
	return file_internal_api_gateway_gateway_proto_rawDescData
}

var file_internal_api_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_gateway_gateway_proto_goTypes = []interface{}{
	(*MsgFormat)(nil),   // 0: pbGateway.MsgFormat
	(*PushMsgReq)(nil),  // 1: pbGateway.PushMsgReq
	(*PushMsgResp)(nil), // 2: pbGateway.PushMsgResp
}
var file_internal_api_gateway_gateway_proto_depIdxs = []int32{
	0, // 0: pbGateway.PushMsgReq.MsgFormat:type_name -> pbGateway.MsgFormat
	1, // 1: pbGateway.Push.PushMsg:input_type -> pbGateway.PushMsgReq
	2, // 2: pbGateway.Push.PushMsg:output_type -> pbGateway.PushMsgResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_gateway_gateway_proto_init() }
func file_internal_api_gateway_gateway_proto_init() {
	if File_internal_api_gateway_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_gateway_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_gateway_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_gateway_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_gateway_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_internal_api_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_internal_api_gateway_gateway_proto_msgTypes,
	}.Build()
	File_internal_api_gateway_gateway_proto = out.File
	file_internal_api_gateway_gateway_proto_rawDesc = nil
	file_internal_api_gateway_gateway_proto_goTypes = nil
	file_internal_api_gateway_gateway_proto_depIdxs = nil
}
