apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-deploy
spec:
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd-container
        image: quay.io/coreos/etcd:v3.4.13
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 2379
          protocol: TCP
        - containerPort: 2380
          protocol: TCP
        volumeMounts:
        - mountPath: /etcd
          name: etcd-etcd
        - mountPath: /etcd-server.etcd
          name: etcd-data
      volumes:
      - name: etcd-etcd
        persistentVolumeClaim:
          claimName: etcd-etcd
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: etcd-etcd
 namespace: etcd01
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: etcd-data
 namespace: etcd01
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: etcd01
  labels:
    name: etcd
spec:
  ports:
  - name: etcd-01
    protocol: TCP
    targetPort: 2379
    port: 2379
  - name: etcd-02
    protocol: TCP
    targetPort: 2380
    port: 2380
  selector:
    app: etcd
