apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-deploy
  namespace: app-namespace
  labels:
    app: mysql
spec:
  serviceName: mysql-svc
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql-container-port
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim