apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: app-namespace
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  clusterIP: None # 有状态应用不需要为 service 分配域名了