apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  namespace: app-namespace
  labels:
    app: redis
spec:
  serviceName: redis-svc

  volumeClaimTemplates:
    - metadata:
        name: redis-100m-pvc
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 100Mi

  volumes:
    - name: config 
      configMap:
        name: redis-config
  
  replicas: 1
  selector:
    matchLabels:
      app: redis
  
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.7
        command:
          - "sh"
          - "-c"
          - "redis-server /usr/local/redis/redis.conf"
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "1000m"
        # livenessProbe:
        #   tcpSocket:
        #     port: 6379
        #   initialDelaySeconds: 300
        #   timeoutSeconds: 1
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 3
        # readinessProbe:
        #   tcpSocket:
        #     port: 6379
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 3
        volumeMounts:
          - name: config 
            mountPath: /usr/local/redis/redis.conf
          - name: redis-100m-pvc
            mountPath: /data