apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: app-namespace
  labels:
    app: redis
data:
  redis.conf: |- 
    dir /srv
    port 6379
    bind 0.0.0.0
    appendonly yes
    daemonize no 
    requirepass test
    pidfile /srv/redis-6379.pid