apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: geraldkohn

spec:
  selector:
    matchLabels:
      app: mongo-sts
  serviceName: mongo-svc
  replicas: 1

  template:
    metadata:
      labels:
        app: mongo-sts
    spec:
      containers:
      - name: mongodb
        image: mongo:4.2.24
        ports:
        - containerPort: 27017
          name: mongo
        # volumeMounts:
        # - name: mongo-local-1g-pvc
        #   mountPath: /data
        # env:
        #   - name: MONGO_INITDB_ROOT_USERNAME
        #     value: root
        #   - name: MONGO_INITDB_ROOT_PASSWORD
        #     value: root

  # volumeClaimTemplates:
  # - metadata:
  #     name: mongo-local-1g-pvc
  #     namespace: geraldkohn
  #   spec:
  #     storageClassName: mongo-storage-class
  #     accessModes: 
  #     - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 1Gi
