apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
  namespace: geraldkohn
spec:
  selector:
    matchLabels:
      app: mysql-sts
  serviceName: mysql-svc
  replicas: 1

  template:
    metadata:
      labels:
        app: mysql-sts
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-local-1g-pvc
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-local-1g-pvc
      namespace: geraldkohn
    spec:
      storageClassName: mysql-storage-class
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
