---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: geraldkohn
spec:
  selector:
    matchLabels:
      app: gateway # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: gateway # 标签
    spec:
      containers:
      - name: gateway
        image: geraldkohn/im-gateway
        imagePullPolicy: Always
        ports:
        - name: rpc-port
          containerPort: 8020
        - name: http-port
          containerPort: 8021
        - name: ws-port
          containerPort: 8022
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: geraldkohn
spec:
  ports:
    - name: rpc-port
      protocol: TCP
      port: 8020
      targetPort: 8020
    - name: http-port
      protocol: TCP
      port: 8021
      targetPort: 8021
    - name: ws-port
      protocol: TCP
      port: 8022
      targetPort: 8022
  selector:
    app: gateway
  type: NodePort
