apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: geraldkohn
spec:
  selector:
    app: mongo-sts
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  clusterIP: None
