apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: geraldkohn
spec:
  selector:
    app: etcd-sts
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
    name: client
  - port: 2380
    targetPort: 2380
    protocol: TCP
    name: peer
  clusterIP: None
